---
- hosts: all
  tasks:
    - name: Instalar dependencias
      yum:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - fontconfig
        - postgresql-devel
        - libxml2-devel
        - expat-devel
        - libssh2-devel

    - unarchive:
        src: http://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
        dest: /tmp
        creates: /usr/local/bin/phantomjs
        remote_src: True

    - copy:
        src: /tmp/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
        dest: /usr/local/bin/phantomjs
        force: no
        owner: root
        group: root
        mode: 755

  roles:
      - {role: dmanto.plenv-and-carton, app_user: "bam", plenv_local_version: "5.24.1"}
      - {role: dmanto.perl-dbd-oracle, app_user: "bam"}
      - {role: DavidWittman.redis, redis_version: 3.2.7}
